version: "3.9"

services:
  whoami:
    image: containous/whoami@sha256:3c935b9746f80ae5bad92a2b6f917ec9348977f299cdf361b6672d8ebd1fb755
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.cloud.d4rkcyber.xyz`)"
      - "traefik.http.routers.whoami.entrypoints=https"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks:
      - proxy

  monitoring:
    image: nicolargo/glances@sha256:6eec04b3ae5460f4469d90a8897b7469715973ca6aef209d961f26fb9c9086a7
    restart: unless-stopped
    pid: host
    privileged: true
    networks:
      - proxy
    #network_mode: "host"
    ports:
      - "61208:61208"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro"
      - "./glances.conf:/glances/conf/glances.conf"
    environment:
      - TZ=${TZ}
      - "GLANCES_OPT=-C /glances/conf/glances.conf -w"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glances.rule=Host(`glances.cloud.d4rkcyber.xyz`)"
      - "traefik.http.routers.glances.entrypoints=https"
      - "traefik.http.routers.glances.tls=true"
      - "traefik.http.services.glances.loadbalancer.server.port=61208"

networks:
  proxy:
    external: true

#This configuration file is used to define the services that will be running in the Glances stack.
#The services are defined in the services section, where each service is defined by a name and a set of configuration options.
#This stack would be used to monitor the health of the services running in the stack.
#copy the content of the file and paste it in the compose.yaml file in the glances directory.
#run the command docker-compose up -d to start the services.
#The services will be started in the background and can be accessed using the browser by visiting the URL http://localhost:61208.
#The Glances service will be running on port 61208 and the Whoami service will be running on port 80.
#The Glances service will be used to monitor the health of the services running in the stack, while the Whoami service will be used to display the hostname of the container.