services:
  grafana:
    image: grafana/grafana:11.3.1
    container_name: grafana
    user: "1000"
    environment:
      - TZ=Europe/Dublin
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3002:3000
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.local.d4rkcyber.xyz`)"
      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.services.grafana.loadbalancer.server.scheme=http"

networks:
  proxy:
    name: proxy
    external: true

volumes:
  grafana-storage: {}