services:
  firefox:
    image: jlesage/firefox:latest
    container_name: firefox-vnc
    ports:
      - "5800:5800"  # Web browser access
      - "5900:5900"  # VNC client access
    volumes:
      - ./firefox_config:/config
      - ./firefox_downloads:/config/downloads
    environment:
      - VNC_PASSWORD=damilola  # Optional
      - SECURE_CONNECTION=0    # Set to 1 for encrypted connection [10]
    restart: unless-stopped
    networks:
      - proxy
    shm_size: '2gb'            # Prevents browser crashes
    mem_limit: 3g              # Caps max memory usage
    mem_reservation: 1g    
    dns:
      - 192.168.2.1
      - 8.8.8.8
      - 1.1.1.1

networks:
  proxy:
    name: proxy
    external: true