services:
  prometheus:
    image: dhi.io/prometheus:3 #prom/prometheus:v3.13.2
    container_name: prometheus
    user: "1001"
    environment:
      - TZ=Europe/Dublin
    command:
      - '--web.enable-remote-write-receiver'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=7d'
    volumes:
      - ./prometheus/:/etc/prometheus
      - ./prom_data/:/data
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
       - proxy
  
  node-exporter:
    image: dhi.io/node-exporter:1 #prom/node-exporter:v1.8.2
    container_name: node-exporter
    networks:
      - proxy
    ports:
      - 9100:9100
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($|/)"


  blackbox-exporter:
    image: prom/blackbox-exporter:v0.27.0
    container_name: blackbox-exporter
    command:
      - --config.file=/etc/blackbox_exporter/config.yml
    volumes:
      - ./blackbox/:/etc/blackbox_exporter:ro
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    name: proxy
    external: true
